export const SERVER = 'http://localhost:5000/api'
export const ROOT = '/'
export const AUTH = '/auth'
export const SIGN_IN = '/signIn'
export const SIGN_UP = '/signUp'
export const GALLERY = '/gallery'
export const ADD_IMAGE = '/addImage'
export const DELETE_IMAGE = '/deleteImage'